version: "3.9"

services:
    mysql:
        image: mysql:5.7.28
        container_name: exagon-mysql
        ports:
            - 4406:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD={MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql    

volumes:
    mysql_data:
