version: "3.9"

services:
    nginx:
        image: nginx:1.21.0-alpine
        container_name: exagon-service1
        restart: on-failure
        ports:
            - "8880:80"
        volumes:
            - ../../services/symfony:/var/www/symfony
            - './default.conf:/etc/nginx/conf.d/default.conf'
    php:
        container_name: exagon-service1-api
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        user: "1000:1000"
        volumes:
            - ../../services/symfony:/var/www/symfony
