version: '3.9'

services:
    mariadb:
        image: mariadb:10.7
        container_name: exagon-mariadb
        ports:
            - 4407:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD={MYSQL_PASSWORD}
        volumes:
            - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
